GuanceCloud/cliutils

.gitignore
cmd/diskcache/Makefile
cmd/diskcache/main.go
diskcache/README.md
diskcache/diskcache.go
diskcache/drop.go
diskcache/get.go
diskcache/lock.go
diskcache/metric.go
diskcache/metric_test.go
diskcache/open.go
diskcache/options.go
diskcache/put.go
diskcache/put_test.go
diskcache/rotate.go
diskcache/switch.go
vendor/modules.txt

remove logging in diskcache
add more metrics to diskcache

add cmds to write runable binary under different platforms

---

point/lp.go

Fix parsing line protocol causing crash

---

dialtesting/http.go

fix some bugs:
- fix new http request body size
- fix http request header `Host` set failed

Fix dialtesting http request error and host header set failed

---

dialtesting/websocket.go

Fix dialtesting websocket host

---

network/http/gin.go
network/http/gin_test.go

- Reduce the restrictions on CORS "Access-Control-Allow-Headers"
- Add CORS "Access-Control-Max-Age" to reduce OPTIONS requests

reduce the restrictions on CORS Access-Control-Allow-Headers

---

dialtesting/http.go

fix http dialtesting download time

fix: fix dialtesting http download time

---

go.mod
go.sum
logger/root.go
vendor/github.com/robfig/cron/v3/.gitignore
vendor/github.com/robfig/cron/v3/.travis.yml
vendor/github.com/robfig/cron/v3/LICENSE
vendor/github.com/robfig/cron/v3/README.md
vendor/github.com/robfig/cron/v3/chain.go
vendor/github.com/robfig/cron/v3/constantdelay.go
vendor/github.com/robfig/cron/v3/cron.go
vendor/github.com/robfig/cron/v3/doc.go
vendor/github.com/robfig/cron/v3/logger.go
vendor/github.com/robfig/cron/v3/option.go
vendor/github.com/robfig/cron/v3/parser.go
vendor/github.com/robfig/cron/v3/spec.go
vendor/modules.txt

InitCustomizeRoot use github.com/robfig/cron/v3 as a timer.

feat: use cron

---

network/ws/epoll_linux.go
pipeline/ptinput/funcs/all.go
pipeline/ptinput/funcs/all_doc.go
pipeline/ptinput/funcs/all_doc_en.go
pipeline/ptinput/funcs/fn_pt_name.go
pipeline/ptinput/funcs/fn_pt_name_test.go
pipeline/ptinput/funcs/fn_set_measurement.go
pipeline/ptinput/funcs/md/pt_name.en.md
pipeline/ptinput/funcs/md/pt_name.md
pipeline/ptinput/funcs/utils.go

feat:  add pipeline function `pt_name`

---

logger/logger_ctx.go
logger/logger_test.go
logger/opt.go

feat:
1.  Supports log printing of tracing information

feat: Supports log printing of tracing information

---

network/http/err.go
network/http/err_test.go

Fix httpErr weakness

---

pipeline/ptinput/funcs/md/agg_create.en.md
pipeline/ptinput/funcs/md/agg_create.md
pipeline/ptinput/funcs/md/agg_metric.en.md
pipeline/ptinput/funcs/md/agg_metric.md
pipeline/ptinput/funcs/md/create_point.en.md
pipeline/ptinput/funcs/md/create_point.md
pipeline/ptinput/funcs/md/mquery_refer_table.en.md
pipeline/ptinput/funcs/md/mquery_refer_table.md
pipeline/ptinput/funcs/md/query_refer_table.en.md
pipeline/ptinput/funcs/md/query_refer_table.md

update Pipeline functions document

---

go.mod
go.sum
vendor/github.com/influxdata/influxdb1-client/models/inline_strconv_parse.go
vendor/github.com/influxdata/influxdb1-client/models/points.go
vendor/modules.txt

merge replace package influxdb1-client to v0.1.5

Fix lp parse panic

---

dialtesting/http.go
dialtesting/icmp.go
dialtesting/task.go
dialtesting/tcp.go
dialtesting/websocket.go

add `GetHostName` method to get hostname for each dialtesting task

feat(dialtesting): add hostname method

---

pipeline/manager/script.go
pipeline/manager/scriptstore.go
pipeline/ptinput/funcs/all.go
pipeline/ptinput/funcs/all_doc.go
pipeline/ptinput/funcs/all_doc_en.go
pipeline/ptinput/funcs/fn_cache.go
pipeline/ptinput/funcs/fn_cache_test.go
pipeline/ptinput/funcs/fn_http_request.go
pipeline/ptinput/funcs/fn_http_request_test.go
pipeline/ptinput/funcs/md/cache_get.en.md
pipeline/ptinput/funcs/md/cache_get.md
pipeline/ptinput/funcs/md/cache_set.en.md
pipeline/ptinput/funcs/md/cache_set.md
pipeline/ptinput/funcs/md/http_request.en.md
pipeline/ptinput/funcs/md/http_request.md
pipeline/ptinput/plcache/cache.go
pipeline/ptinput/plcache/cache_test.go
pipeline/ptinput/point.go

add http request func and cache module

---

point/decode.go
point/json.go

add default time to point when timestamp is zero

fix(point): add current time when point time is zero

---

dialtesting/http.go
dialtesting/icmp.go
dialtesting/task.go
dialtesting/tcp.go
dialtesting/websocket.go

add workspace language and tags info

fix(dialtesting): add workspace language and tags info

---

pipeline/ptinput/ptwindow/pt_window.go

Bug fix: Incorrect recycling of objects in Pipeline point window

---

pipeline/ptinput/funcs/all.go
pipeline/ptinput/funcs/all_doc.go
pipeline/ptinput/funcs/fn_slice_string.go
pipeline/ptinput/funcs/fn_slice_string_test.go
pipeline/ptinput/funcs/md/slice_string.en.md
pipeline/ptinput/funcs/md/slice_string.md

pipeline 新增以下函数支持字符串子串提取：
`fn slice_string(name: str, start: int, end: int) -> str`

Add pipeline functions

---

dialtesting/http.go
dialtesting/http_script.go
dialtesting/http_script_test.go
dialtesting/http_test.go
dialtesting/icmp.go
dialtesting/icmp_test.go
dialtesting/multi.go
dialtesting/multi_test.go
dialtesting/task.go
dialtesting/tcp.go
dialtesting/tcp_test.go
dialtesting/websocket.go
dialtesting/websocket_test.go

add mutli type of dialtesting task

feat(dialtesting): add multi type of task

---

network/http/gin.go

Http option

---

dialtesting/http.go
dialtesting/multi.go
dialtesting/task.go

fix(dialtesting): fix http user-agent
